"""i add likes and comment to post schema

Revision ID: 810652708f47
Revises: c4d098d88af3
Create Date: 2026-09-06 18:36:53.094187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '810652708f47'
down_revision: Union[str, Sequence[str], None] = 'c4d098d88af3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('likes', sa.Integer(), server_default='0', nullable=False))
    op.add_column('posts', sa.Column('comments', sa.Text(), server_default='', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'comments')
    op.drop_column('posts', 'likes')
    # ### end Alembic commands ###
